#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# название маршрута "app_lucky_number" пока не важно
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number

blog_list:
    path: /blog
    controller: App\Controller\BlogController::blog_list

api_post_show:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::show
    methods:    GET|HEAD

api_post_edit:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::edit
    methods:    PUT
    
contact:
    path:       /contact
    controller: 'App\Controller\DefaultController::contact'
    condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
    # expressions can also include config parameters:
    # condition: "request.headers.get('User-Agent') matches '%app.allowed_browsers%'"

