#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# название маршрута "app_lucky_number" пока не важно
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
